# Generated by Django 5.1 on 2024-08-13 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(max_length=255)),
                ('contact_person', models.CharField(max_length=255)),
                ('contact_email', models.EmailField(max_length=254, unique=True)),
                ('contact_phone_number', models.CharField(max_length=15)),
                ('address', models.CharField(max_length=255)),
                ('location_latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('location_longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('business_hours', models.CharField(max_length=255)),
                ('services_offered', models.TextField()),
                ('accepted_file_formats', models.CharField(max_length=255)),
                ('pricing_information', models.TextField()),
                ('payment_methods', models.CharField(max_length=255)),
                ('terms_and_conditions', models.TextField()),
                ('printer_specifications', models.TextField(blank=True, null=True)),
                ('vendor_logo', models.ImageField(blank=True, null=True, upload_to='vendor_logos/')),
                ('reviews_and_ratings', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
