# Generated by Django 5.1 on 2024-08-20 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendor',
            name='vendor_logo',
        ),
        migrations.AddField(
            model_name='vendor',
            name='vendor_logo_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
